-- m_data_import_setting テーブルへのデータ挿入
INSERT INTO m_data_import_setting (
    profile_id, usage_nm, group_company_cd, target_entity, 
    character_cd, delimiter, header_row_index, skip_row_count, is_active,
    cre_at, upd_at
) VALUES 
(1, 'KM-PROCUDT', 'KM', 'PRODUCT', 'UTF-8', ',', 1, 0, true, current_timestamp, current_timestamp),
(2, 'RKE-PROCUDT', 'RKE', 'PRODUCT', 'UTF-8', ',', 1, 0, true, current_timestamp, current_timestamp);

-- m_fixed_to_attr_map テーブルへのデータ挿入
INSERT INTO m_fixed_to_attr_map 
(
    map_id, group_company_cd, data_kind, attr_cd, 
    source_id_column, source_label_column, 
    value_role, data_type_override, split_mode, 
    is_active, priority, fixed_remarks
) VALUES 
(1, 'KM', 'PRODUCT', 'BRAND', 'source_brand_id', 'source_brand_nm', 'ID_AND_LABEL', 'NULL', 'NULL', 'TRUE', 1, NULL),
(2, 'KM', 'PRODUCT', 'CATEGORY_1', 'source_category_1_id', 'source_category_1_nm', 'ID_AND_LABEL', 'NULL', 'NULL', 'TRUE', 1, NULL),
(3, 'KM', 'PRODUCT', 'CATEGORY_2', 'source_category_2_id', 'source_category_2_nm', 'ID_AND_LABEL', 'NULL', 'NULL', 'TRUE', 1, NULL),
(4, 'KM', 'PRODUCT', 'CATEGORY_3', 'source_category_3_id', 'source_category_3_nm', 'ID_AND_LABEL', 'NULL', 'NULL', 'TRUE', 1, NULL),
(5, 'KM', 'PRODUCT', 'PRODUCT_STATUS', 'source_product_status_cd', 'source_product_status_nm', 'ID_AND_LABEL', 'NULL', 'NULL', 'TRUE', 1, NULL),
(6, 'KM', 'PRODUCT', 'NEW_USED_KBN', 'source_new_used_kbn', '""', 'ID_ONLY', 'NULL', 'NULL', 'TRUE', 1, NULL),
(7, 'KM', 'PRODUCT', 'STOCK_EXISTENCE', 'source_stock_existence_cd', 'source_stock_existence_nm', 'ID_AND_LABEL', 'NULL', 'NULL', 'TRUE', 1, NULL),
(8, 'KM', 'PRODUCT', 'SALE_STATUS', 'source_sale_permission_cd', 'source_sale_permission_nm', 'ID_AND_LABEL', 'NULL', 'NULL', 'TRUE', 1, NULL),
(9, 'KM', 'PRODUCT', 'TRANSFER_STATUS', 'source_transfer_status', '""', 'ID_ONLY', 'NULL', 'NULL', 'TRUE', 1, NULL),
(10, 'KM', 'PRODUCT', 'REPAIR_STATUS', 'source_repair_status', '""', 'ID_ONLY', 'NULL', 'NULL', 'TRUE', 1, NULL),
(11, 'KM', 'PRODUCT', 'RESERVATION_STATUS', 'source_reservation_status', '""', 'ID_ONLY', 'NULL', 'NULL', 'TRUE', 1, NULL),
(12, 'KM', 'PRODUCT', 'CONSIGNMENT_STATUS', 'source_consignment_status', '""', 'ID_ONLY', 'NULL', 'NULL', 'TRUE', 1, NULL),
(13, 'KM', 'PRODUCT', 'CONSIGNMENT_STATUS', 'source_accept_status', '""', 'ID_ONLY', 'NULL', 'NULL', 'TRUE', 1, NULL),
(14, 'KM', 'PRODUCT', 'EC_LISTING_STATUS', 'source_ec_listing_kbn', '""', 'ID_ONLY', 'NULL', 'NULL', 'TRUE', 1, NULL),
(15, 'KM', 'PRODUCT', 'PURCHASE_RANK', 'source_purchase_rank', 'source_purchase_rank_name', 'ID_AND_LABEL', 'NULL', 'NULL', 'TRUE', 1, NULL),
(16, 'KM', 'PRODUCT', 'SALES_RANK', 'source_sales_rank', 'source_sales_rank_name', 'ID_AND_LABEL', 'NULL', 'NULL', 'TRUE', 1, NULL);

INSERT INTO m_data_import_d (
    profile_id, column_seq, target_entity, attr_cd, 
    target_column, cast_type, transform_expr, is_required,
    import_remarks) VALUES 
(1, 0, 'PRODUCT_MST', 'GP_CD', 'group_company_cd', 'TEXT', NULL, 'TRUE', 'S3より取得した暗黙値（KM）でプログラミング補完'),
(1, 1, 'PRODUCT_MST', 'PRODUCT_CD', 'product_cd', 'TEXT', 'trim(@)', 'TRUE', '商品コード必須'),
(1, 2, 'PRODUCT_MST', 'PRODUCT_MANAGEMENT_CD', 'product_management_cd', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 3, 'PRODUCT_MST', 'BRAND_ID', 'brand_id', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 4, 'PRODUCT_MST', 'BRAND_NM', 'brand_nm', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 5, 'PRODUCT_MST', 'CATEGORY_1_ID', 'category_1_id', 'TEXT', 'trim(@)', 'TRUE', '大カテゴリ必須'),
(1, 6, 'PRODUCT_MST', 'CATEGORY_1_NM', 'category_1_nm', 'TEXT', 'trim(@)', 'TRUE', '大カテゴリ必須'),
(1, 7, 'PRODUCT_MST', 'CATEGORY_2_ID', 'category_2_id', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 8, 'PRODUCT_MST', 'CATEGORY_2_NM', 'category_2_nm', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 9, 'PRODUCT_MST', 'CATEGORY_3_ID', 'category_3_id', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 10, 'PRODUCT_MST', 'CATEGORY_3_NM', 'category_3_nm', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 11, 'PRODUCT_MST', 'PRODUCT_STATUS_CODE', 'product_status_code', 'TEXT', 'trim(@)', 'TRUE', '商品状態必須'),
(1, 12, 'PRODUCT_MST', 'PRODUCT_STATUS_NM', 'product_status_nm', 'TEXT', 'trim(@)', 'TRUE', '商品状態必須'),
(1, 13, 'PRODUCT_MST', 'NEW_USED_KBN', 'new_used_kbn', 'TEXT', 'trim(@)', 'TRUE', '新品区分必須'),
(1, 14, 'PRODUCT_MST', 'QUANTITY', 'quantity', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 15, 'PRODUCT_MST', 'STOCK_EXISTENCE_CD', 'stock_existence_cd', 'TEXT', 'trim(@)', 'TRUE', '在庫有無必須'),
(1, 16, 'PRODUCT_MST', 'STOCK_EXISTENCE_NM', 'stock_existence_nm', 'TEXT', 'trim(@)', 'TRUE', '在庫有無必須'),
(1, 17, 'PRODUCT_MST', 'SALE_PERMISSION_CD', 'sale_permission_cd', 'TEXT', 'trim(@)', 'TRUE', '販売可否必須'),
(1, 18, 'PRODUCT_MST', 'SALE_PERMISSION_NM', 'sale_permission_nm', 'TEXT', 'trim(@)', 'TRUE', '販売可否必須'),
(1, 19, 'PRODUCT_MST', 'TRANSFER_STATUS', 'transfer_status', 'TEXT', 'trim(@)', 'TRUE', '移動状態必須'),
(1, 20, 'PRODUCT_MST', 'REPAIR_STATUS', 'repair_status', 'TEXT', 'trim(@)', 'TRUE', '修理状態必須'),
(1, 21, 'PRODUCT_MST', 'RESERVATION_STATUS', 'reservation_status', 'TEXT', 'trim(@)', 'TRUE', '予約状態必須'),
(1, 22, 'PRODUCT_MST', 'CONSIGNMENT_STATUS', 'consignment_status', 'TEXT', 'trim(@)', 'TRUE', '委託状態必須'),
(1, 23, 'PRODUCT_MST', 'SOURCE_ACCEPT_STATUS', 'accept_status', 'TEXT', 'trim(@)', 'TRUE', '受託状態必須'),
(1, 24, 'PRODUCT_MST', 'EC_LISTING_KBN', 'ec_listing_kbn', 'TEXT', 'trim(@)', 'TRUE', 'EC掲載必須'),
(1, 25, 'PRODUCT_MST', 'ASSESSMENT_PRICE_EXCL_TAX', 'assessment_price_excl_tax', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 26, 'PRODUCT_MST', 'ASSESSMENT_PRICE_INCL_TAX', 'assessment_price_incl_tax', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 27, 'PRODUCT_MST', 'ASSESSMENT_TAX_RATE', 'assessment_tax_rate', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 28, 'PRODUCT_MST', 'PURCHASE_PRICE_EXCL_TAX', 'purchase_price_excl_tax', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 29, 'PRODUCT_MST', 'PURCHASE_PRICE_INCL_TAX', 'purchase_price_incl_tax', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 30, 'PRODUCT_MST', 'PURCHASE_TAX_RATE', 'purchase_tax_rate', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 31, 'PRODUCT_MST', 'DISPLAY_PRICE_EXCL_TAX', 'display_price_excl_tax', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 32, 'PRODUCT_MST', 'DISPLAY_PRICE_INCL_TAX', 'display_price_incl_tax', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 33, 'PRODUCT_MST', 'DISPLAY_TAX_RATE', 'display_tax_rate', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 34, 'PRODUCT_MST', 'SALES_PRICE_EXCL_TAX', 'sales_price_excl_tax', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 35, 'PRODUCT_MST', 'SALES_PRICE_INCL_TAX', 'sales_price_incl_tax', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 36, 'PRODUCT_MST', 'SALES_TAX_RATE', 'sales_tax_rate', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 37, 'PRODUCT_MST', 'PURCHASE_RANK', 'purchase_rank', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 38, 'PRODUCT_MST', 'PURCHASE_RANK_NAME', 'purchase_rank_name', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 39, 'PRODUCT_MST', 'SALES_RANK', 'sales_rank', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 40, 'PRODUCT_MST', 'SALES_RANK_NAME', 'sales_rank_name', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 41, 'PRODUCT_MST', 'SALES_CHANNEL_NM', 'sales_channel_nm', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 42, 'PRODUCT_MST', 'SALES_CHANNEL_REGION', 'sales_channel_region', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 43, 'PRODUCT_MST', 'SALES_CHANNEL_METHOD', 'sales_channel_method', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 44, 'PRODUCT_MST', 'SALES_CHANNEL_TARGET', 'sales_channel_target', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 45, 'PRODUCT_MST', 'PURCHASE_CHANNEL_NM', 'purchase_channel_nm', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 46, 'PRODUCT_MST', 'PURCHASE_CHANNEL_REGION', 'purchase_channel_region', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 47, 'PRODUCT_MST', 'PURCHASE_CHANNEL_METHOD', 'purchase_channel_method', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 48, 'PRODUCT_MST', 'PURCHASE_CHANNEL_TARGET', 'purchase_channel_target', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 49, 'PRODUCT_MST', 'STORE_ID', 'store_id', 'TEXT', 'trim(@)', 'TRUE', '店舗必須'),
(1, 50, 'PRODUCT_MST', 'STORE_NM', 'store_nm', 'TEXT', 'trim(@)', 'TRUE', '店舗必須'),
(1, 51, 'PRODUCT_MST', 'CONSIGNOR_GROUP_COMPANY_ID', 'consignor_group_company_id', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 52, 'PRODUCT_MST', 'CONSIGNOR_PRODUCT_CD', 'consignor_product_cd', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 53, 'EAV', 'SPECIAL_NOTES', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 54, 'EAV', 'DEFECT_NOTES', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 55, 'EAV', 'CATALOG_DESC', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 56, 'EAV', 'PRODUCT_REMARKS', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 57, 'EAV', 'REPAIR_HISTORY', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 58, 'EAV', 'BUYER_STAFF', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 59, 'EAV', 'SUPPLIER_CD', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 60, 'EAV', 'SUPPLIER_TYPE', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 61, 'EAV', 'SUPPLIER_STORE', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 62, 'EAV', 'PURCHASE_DATE', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 63, 'EAV', 'PROCESSING_FEE', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 64, 'EAV', 'REFERENCE_PRICE', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 65, 'EAV', 'REFERENCE_PRICE_UPDATED_AT', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 66, 'EAV', 'SALES_START_DATE', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 67, 'EAV', 'SALES_END_DATE', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 68, 'EAV', 'GENDER', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 69, 'EAV', 'PRODUCT_ALIAS', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 70, 'EAV', 'PRODUCT_LINE', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 71, 'EAV', 'MODEL_NO', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 72, 'EAV', 'CASE_NO', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 73, 'EAV', 'DIAL_COLOR', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 74, 'EAV', 'MAIN_COLOR', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 75, 'EAV', 'CASE_BAND_MATERIAL', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 76, 'EAV', 'BAND_COLOR', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 77, 'EAV', 'DIAL_PATTERN', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 78, 'EAV', 'CASE_MATERIAL', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 79, 'EAV', 'MODEL_YEAR', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 80, 'EAV', 'SIZE_WRIST', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 81, 'EAV', 'CASE_HEIGHT_ACTUAL', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 82, 'EAV', 'MOVEMENT', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 83, 'EAV', 'WEIGHT', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 84, 'EAV', 'CASE_WIDTH_ACTUAL', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 85, 'EAV', 'CASE_DEPTH_ACTUAL', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 86, 'EAV', 'CASE_HEIGHT', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 87, 'EAV', 'CASE_WIDTH', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 88, 'EAV', 'CASE_DEPTH', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 89, 'EAV', 'STANDARD_SIZE', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 90, 'EAV', 'ACCESSORIES', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 91, 'EAV', 'WATER_RESIST', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 92, 'EAV', 'FUNCTIONS', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 93, 'EAV', 'CASE_SHAPE', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 94, 'EAV', 'WARRANTY_TYPE', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 95, 'EAV', 'WARRANTY_DATE', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 96, 'EAV', 'MADE_IN', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 97, 'EAV', 'SERIAL_NO', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 98, 'EAV', 'BODY_MATERIAL', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 99, 'EAV', 'BODY_COLOR', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 100, 'EAV', 'METAL_MATERIAL', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 101, 'EAV', 'DATE_CODE', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 102, 'EAV', 'BODY_PATTERN', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 103, 'EAV', 'ENGRAVING', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 104, 'EAV', 'WIDTH', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 105, 'EAV', 'DEPTH', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 106, 'EAV', 'HEIGHT', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 107, 'EAV', 'WIDTH_ACTUAL', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 108, 'EAV', 'DEPTH_ACTUAL', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 109, 'EAV', 'HEIGHT_ACTUAL', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 110, 'EAV', 'CARD_SLOT_COUNT', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 111, 'EAV', 'POCKET_IN_COUNT', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 112, 'EAV', 'POCKET_OUT_COUNT', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 113, 'EAV', 'SERIAL_POSITION', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 114, 'EAV', 'COLLAB_BRAND', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 115, 'EAV', 'DESIGN_PERIOD', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 116, 'EAV', 'SEASON', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 117, 'EAV', 'PATTERN', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 118, 'EAV', 'MATERIAL', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 119, 'EAV', 'SIZE_ACTUAL', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 120, 'EAV', 'SIZE_NOTE', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 121, 'EAV', 'BODY_WIDTH', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 122, 'EAV', 'BODY_LENGTH', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 123, 'EAV', 'SLEEVE_LENGTH', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 124, 'EAV', 'SHOULDER_WIDTH', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 125, 'EAV', 'TOTAL_LENGTH', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 126, 'EAV', 'WAIST', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 127, 'EAV', 'INSEAM', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 128, 'EAV', 'HEEL_HEIGHT', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 129, 'EAV', 'HEIGHT', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 130, 'EAV', 'LENGTH', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 131, 'EAV', 'METAL_PURITY', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 132, 'EAV', 'GEM_MAIN_MATERIAL', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 133, 'EAV', 'GEM_SIDE_MATERIAL', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 134, 'EAV', 'RING_SIZE_JP', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 135, 'EAV', 'RING_SIZE_US', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 136, 'EAV', 'ORIGIN', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 137, 'EAV', 'DIAMOND_COLOR', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 138, 'EAV', 'GEM_COLOR', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 139, 'EAV', 'DIAMOND_CUT', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 140, 'EAV', 'CARAT_MAIN', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 141, 'EAV', 'CARAT_SIDE', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 142, 'EAV', 'FLUORESCENCE', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 143, 'EAV', 'ERA', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 144, 'EAV', 'CERT_AGENCY', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 145, 'EAV', 'GEM_TREATMENT', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 146, 'EAV', 'CERTIFICATE', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 147, 'EAV', 'DIAMOND_CLARITY', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 148, 'EAV', 'GEM_MAIN_DIAMETER', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 149, 'EAV', 'MOTIF', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL),
(1, 150, 'EAV', 'VINTAGE_FLAG', 'NULL', 'TEXT', 'trim(@)', 'FALSE', NULL);
