-- m_company テーブルへのデータ挿入
INSERT INTO m_company (
    group_company_id, 
    group_company_cd, 
    group_company_nm, 
    default_currency_cd, 
    is_active,
    cre_at,
    upd_at
) VALUES 
(1, 'KM', 'KOMEHYO', 'JPY', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'RKE', 'ロデオドライブ', 'JPY', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'KBO', 'ブランドオフ', 'JPY', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (group_company_id) DO UPDATE SET
    group_company_cd = EXCLUDED.group_company_cd,
    group_company_nm = EXCLUDED.group_company_nm,
    default_currency_cd = EXCLUDED.default_currency_cd,
    is_active = EXCLUDED.is_active,
    upd_at = CURRENT_TIMESTAMP;

-- m_data_import_setting テーブルへのデータ挿入
INSERT INTO m_data_import_setting (
    profile_id, usage_nm, group_company_cd, target_entity, 
    character_cd, delimiter, header_row_index, is_active,
    cre_at, upd_at
) VALUES 
(1, 'KM-PROCUDT-TEST1', 'KM', 'PRODUCT', 'UTF-8', ',', 1, true, current_timestamp, current_timestamp),
(2, 'KM-PROCUDT-TEST2', 'RKE', 'PRODUCT', 'SHIFT-JIS', ',', 0, true, current_timestamp, current_timestamp),
(3, 'KM-PROCUDT-TEST3', 'KM', 'PRODUCT', 'UTF-8', ',', 2, false, current_timestamp, current_timestamp),
(4, 'KM-TRN', 'KM', 'EVENT','UTF-8', ',', 1, true, current_timestamp, current_timestamp);

-- -- test data
-- -- m_fixed_to_attr_map テーブルへのデータ挿入
-- INSERT INTO m_fixed_to_attr_map 
-- (
--     map_id, group_company_cd, projection_kind, attr_cd, 
--     source_id_column, source_label_column, 
--     value_role, data_type_override, split_mode, 
--     is_active, priority, fixed_remarks
-- ) VALUES 
-- (1, 'KM', 'PRODUCT', 'BRAND', 'source_brand_id', 'source_brand_nm', 'ID_AND_LABEL', 'NULL', 'NULL', TRUE, 1, NULL),
-- (2, 'KM', 'PRODUCT', 'CATEGORY_1', 'source_category_1_id', 'source_category_1_nm', 'ID_AND_LABEL', 'NULL', 'NULL', TRUE, 1, NULL),
-- (3, 'KM', 'PRODUCT', 'CATEGORY_2', 'source_category_2_id', 'source_category_2_nm', 'ID_AND_LABEL', 'NULL', 'NULL', TRUE, 1, NULL),
-- (4, 'KM', 'PRODUCT', 'CATEGORY_3', 'source_category_3_id', 'source_category_3_nm', 'ID_AND_LABEL', 'NULL', 'NULL', TRUE, 1, NULL),
-- (5, 'KM', 'PRODUCT', 'PRODUCT_STATUS', 'source_product_status_cd', 'source_product_status_nm', 'ID_AND_LABEL', 'NULL', 'NULL', TRUE, 1, NULL),
-- (6, 'KM', 'PRODUCT', 'NEW_USED_KBN', 'source_new_used_kbn', '""', 'ID_ONLY', 'NULL', 'NULL', TRUE, 1, NULL),
-- (7, 'KM', 'PRODUCT', 'STOCK_EXISTENCE', 'source_stock_existence_cd', 'source_stock_existence_nm', 'ID_AND_LABEL', 'NULL', 'NULL', TRUE, 1, NULL),
-- (8, 'KM', 'PRODUCT', 'SALE_STATUS', 'source_sale_permission_cd', 'source_sale_permission_nm', 'ID_AND_LABEL', 'NULL', 'NULL', TRUE, 1, NULL),
-- (9, 'KM', 'PRODUCT', 'TRANSFER_STATUS', 'source_transfer_status', '""', 'ID_ONLY', 'NULL', 'NULL', TRUE, 1, NULL),
-- (10, 'KM', 'PRODUCT', 'REPAIR_STATUS', 'source_repair_status', '""', 'ID_ONLY', 'NULL', 'NULL', TRUE, 1, NULL),
-- (11, 'KM', 'PRODUCT', 'RESERVATION_STATUS', 'source_reservation_status', '""', 'ID_ONLY', 'NULL', 'NULL', TRUE, 1, NULL),
-- (12, 'KM', 'PRODUCT', 'CONSIGNMENT_STATUS', 'source_consignment_status', '""', 'ID_ONLY', 'NULL', 'NULL', TRUE, 1, NULL),
-- (13, 'KM', 'PRODUCT', 'CONSIGNMENT_STATUS', 'source_accept_status', '""', 'ID_ONLY', 'NULL', 'NULL', TRUE, 1, NULL),
-- (14, 'KM', 'PRODUCT', 'EC_LISTING_STATUS', 'source_ec_listing_kbn', '""', 'ID_ONLY', 'NULL', 'NULL', TRUE, 1, NULL),
-- (15, 'KM', 'PRODUCT', 'PURCHASE_RANK', 'source_purchase_rank', 'source_purchase_rank_name', 'ID_AND_LABEL', 'NULL', 'NULL', TRUE, 1, NULL),
-- (16, 'KM', 'PRODUCT', 'SALES_RANK', 'source_sales_rank', 'source_sales_rank_nm', 'ID_AND_LABEL', 'NULL', 'NULL', TRUE, 1, NULL);

INSERT INTO m_fixed_to_attr_map (
    map_id, group_company_cd, projection_kind, attr_cd, source_id_column,
    source_label_column, value_role, data_type_override,
    split_mode, is_active, priority, fixed_remarks
) VALUES 
(1, 'KM', 'PRODUCT', 'BRAND', 'source_brand_id', 'source_brand_nm', 'ID_AND_LABEL', 'NULL', NULL, TRUE, 1, NULL),
(2, 'KM', 'PRODUCT', 'CATEGORY_1', 'source_category_1_id', 'source_category_1_nm', 'ID_AND_LABEL', 'NULL', NULL, TRUE, 1, NULL),
(3, 'KM', 'PRODUCT', 'CATEGORY_2', 'source_category_2_id', 'source_category_2_nm', 'ID_AND_LABEL', 'NULL', NULL, TRUE, 1, NULL),
(4, 'KM', 'PRODUCT', 'CATEGORY_3', 'source_category_3_id', 'source_category_3_nm', 'ID_AND_LABEL', 'NULL', NULL, TRUE, 1, NULL),
(5, 'KM', 'PRODUCT', 'PRODUCT_STATUS', 'source_product_status_cd', 'source_product_status_nm', 'ID_AND_LABEL', 'NULL', NULL, TRUE, 1, NULL),
(6, 'KM', 'PRODUCT', 'NEW_USED_KBN', 'source_new_used_kbn', '""', 'ID_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(7, 'KM', 'PRODUCT', 'STOCK_EXISTENCE', 'source_stock_existence_cd', 'source_stock_existence_nm', 'ID_AND_LABEL', 'NULL', NULL, TRUE, 1, NULL),
(8, 'KM', 'PRODUCT', 'SALE_STATUS', 'source_sale_permission_cd', 'source_sale_permission_nm', 'ID_AND_LABEL', 'NULL', NULL, TRUE, 1, NULL),
(9, 'KM', 'PRODUCT', 'TRANSFER_STATUS', 'source_transfer_status', '""', 'ID_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(10, 'KM', 'PRODUCT', 'REPAIR_STATUS', 'source_repair_status', '""', 'ID_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(11, 'KM', 'PRODUCT', 'RESERVATION_STATUS', 'source_reservation_status', '""', 'ID_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(12, 'KM', 'PRODUCT', 'CONSIGNMENT_STATUS', 'source_consignment_status', '""', 'ID_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(13, 'KM', 'PRODUCT', 'ACCEPT_STATUS', 'source_accept_status', '""', 'ID_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(14, 'KM', 'PRODUCT', 'EC_LISTING_STATUS', 'source_ec_listing_kbn', '""', 'ID_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(15, 'KM', 'PRODUCT', 'PURCHASE_RANK', 'source_purchase_rank', 'source_purchase_rank_name', 'ID_AND_LABEL', 'NULL', NULL, TRUE, 1, NULL),
(16, 'KM', 'PRODUCT', 'SALES_RANK', 'source_sales_rank', 'source_sales_rank_name', 'ID_AND_LABEL', 'NULL', NULL, TRUE, 1, NULL),
(17, 'KM', 'PRODUCT', 'STORE', 'source_store_id', 'source_store_nm', 'ID_AND_LABEL', 'NULL', NULL, TRUE, 1, NULL),
(18, 'KM', 'PRODUCT', 'GP_CD', '""', 'source_group_company_cd', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(19, 'KM', 'PRODUCT', 'PRODUCT_CD', '""', 'source_product_cd', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(20, 'KM', 'PRODUCT', 'PRODUCT_MANAGEMENT_CD', '""', 'source_product_management_cd', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(21, 'KM', 'PRODUCT', 'CATEGORY_LEAF', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(22, 'KM', 'PRODUCT', 'SERIAL_NO', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(23, 'KM', 'PRODUCT', 'PRODUCT_ALIAS', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(24, 'KM', 'PRODUCT', 'PRODUCT_LINE', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(25, 'KM', 'PRODUCT', 'MODEL_NO', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(26, 'KM', 'PRODUCT', 'SALES_START_DATE', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(27, 'KM', 'PRODUCT', 'SALES_END_DATE', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(28, 'KM', 'PRODUCT', 'ACCESSORIES', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(29, 'KM', 'PRODUCT', 'SPECIAL_NOTES', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(30, 'KM', 'PRODUCT', 'DEFECT_NOTES', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(31, 'KM', 'PRODUCT', 'REFERENCE_PRICE', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(32, 'KM', 'PRODUCT', 'REFERENCE_PRICE_UPDATED_AT', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(33, 'KM', 'PRODUCT', 'DISPLAY_PRICE_INCL_TAX', '""', 'source_display_price_incl_tax', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(34, 'KM', 'PRODUCT', 'DISPLAY_PRICE_EXCL_TAX', '""', 'source_display_price_excl_tax', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(35, 'KM', 'PRODUCT', 'CATALOG_DESC', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(36, 'KM', 'PRODUCT', 'PRODUCT_REMARKS', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(37, 'KM', 'PRODUCT', 'SALES_PRICE_INCL_TAX', '""', 'source_sales_price_incl_tax', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(38, 'KM', 'PRODUCT', 'SALES_PRICE_EXCL_TAX', '""', 'source_sales_price_excl_tax', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(39, 'KM', 'PRODUCT_EAV', 'COLLABORATION_BRAND', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(40, 'KM', 'PRODUCT_EAV', 'BODY_PATTERN', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(41, 'KM', 'PRODUCT_EAV', 'BAND_MATERIAL', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(42, 'KM', 'PRODUCT_EAV', 'RING_SIZE_JP', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(43, 'KM', 'PRODUCT_EAV', 'RING_SIZE_US', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(44, 'KM', 'PRODUCT_EAV', 'DEPTH_ACTUAL', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(45, 'KM', 'PRODUCT_EAV', 'GENDER', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(46, 'KM', 'PRODUCT_EAV', 'CERTIFICATE_NO', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(47, 'KM', 'PRODUCT_EAV', 'CERTIFICATE', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(48, 'KM', 'PRODUCT_EAV', 'PURCHASE_PRICE_EXCL_TAX', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(49, 'KM', 'PRODUCT_EAV', 'PURCHASE_DATE', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(50, 'KM', 'PRODUCT_EAV', 'BODY_WIDTH', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(51, 'KM', 'PRODUCT_EAV', 'HEIGHT2', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(52, 'KM', 'PRODUCT_EAV', 'DIAMOND_CLARITY', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(53, 'KM', 'PRODUCT_EAV', 'DESIGN_PERIOD', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(54, 'KM', 'PRODUCT_EAV', 'SERIAL_POSITION', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(55, 'KM', 'PRODUCT_EAV', 'MODEL_YEAR', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(56, 'KM', 'PRODUCT_EAV', 'WARRANTY_DATE', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(57, 'KM', 'PRODUCT_EAV', 'ORIGIN', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(58, 'KM', 'PRODUCT_EAV', 'MADE_IN', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(59, 'KM', 'PRODUCT_EAV', 'ENGRAVING', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(60, 'KM', 'PRODUCT_EAV', 'MAIN_COLOR', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(61, 'KM', 'PRODUCT_EAV', 'BODY_COLOR', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(62, 'KM', 'PRODUCT_EAV', 'PATTERN', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(63, 'KM', 'PRODUCT_EAV', 'DIAL_COLOR', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(64, 'KM', 'PRODUCT_EAV', 'BAND_COLOR', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(65, 'KM', 'PRODUCT_EAV', 'DIAL_PATTERN', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(66, 'KM', 'PRODUCT_EAV', 'MATERIAL', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(67, 'KM', 'PRODUCT_EAV', 'METAL_PURITY', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(68, 'KM', 'PRODUCT_EAV', 'GEM_MAIN_MATERIAL', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(69, 'KM', 'PRODUCT_EAV', 'GEM_SIDE_MATERIAL', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(70, 'KM', 'PRODUCT_EAV', 'BODY_MATERIAL', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(71, 'KM', 'PRODUCT_EAV', 'METAL_MATERIAL', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(72, 'KM', 'PRODUCT_EAV', 'CASE_MATERIAL', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(73, 'KM', 'PRODUCT_EAV', 'STANDARD_SIZE', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(74, 'KM', 'PRODUCT_EAV', 'SIZE_ACTUAL', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(75, 'KM', 'PRODUCT_EAV', 'SIZE_NOTE', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(76, 'KM', 'PRODUCT_EAV', 'SIZE_WRIST', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(77, 'KM', 'PRODUCT_EAV', 'CASE_HEIGHT_ACTUAL', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(78, 'KM', 'PRODUCT_EAV', 'CASE_WIDTH_ACTUAL', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(79, 'KM', 'PRODUCT_EAV', 'CASE_DEPTH_ACTUAL', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(80, 'KM', 'PRODUCT_EAV', 'LENGTH', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(81, 'KM', 'PRODUCT_EAV', 'WIDTH', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(82, 'KM', 'PRODUCT_EAV', 'HEIGHT', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(83, 'KM', 'PRODUCT_EAV', 'WEIGHT', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(84, 'KM', 'PRODUCT_EAV', 'DIAMOND_COLOR', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(85, 'KM', 'PRODUCT_EAV', 'GEM_COLOR', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(86, 'KM', 'PRODUCT_EAV', 'DIAMOND_CUT', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(87, 'KM', 'PRODUCT_EAV', 'CARAT_MAIN', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(88, 'KM', 'PRODUCT_EAV', 'CARAT_SIDE', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(89, 'KM', 'PRODUCT_EAV', 'CARD_SLOT_COUNT', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(90, 'KM', 'PRODUCT_EAV', 'POCKET_IN_COUNT', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(91, 'KM', 'PRODUCT_EAV', 'POCKET_OUT_COUNT', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(92, 'KM', 'PRODUCT_EAV', 'FLUORESCENCE', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(93, 'KM', 'PRODUCT_EAV', 'WATER_RESIST', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(94, 'KM', 'PRODUCT_EAV', 'FUNCTIONS', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(95, 'KM', 'PRODUCT_EAV', 'MOVEMENT', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(96, 'KM', 'PRODUCT_EAV', 'CASE_SHAPE', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(97, 'KM', 'PRODUCT_EAV', 'SEASON', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(98, 'KM', 'PRODUCT_EAV', 'ERA', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(99, 'KM', 'PRODUCT_EAV', 'CERTIFICATE_AGENCY', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(100, 'KM', 'PRODUCT_EAV', 'GEM_TREATMENT', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(101, 'KM', 'PRODUCT_EAV', 'WARRANTY_TYPE', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(102, 'KM', 'PRODUCT_EAV', 'DATE_CODE', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(103, 'KM', 'PRODUCT_EAV', 'BODY_LENGTH', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(104, 'KM', 'PRODUCT_EAV', 'SLEEVE_LENGTH', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(105, 'KM', 'PRODUCT_EAV', 'SHOULDER_WIDTH', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(106, 'KM', 'PRODUCT_EAV', 'TOTAL_LENGTH', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(107, 'KM', 'PRODUCT_EAV', 'WAIST', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(108, 'KM', 'PRODUCT_EAV', 'INSEAM', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(109, 'KM', 'PRODUCT_EAV', 'HEEL_HEIGHT', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(110, 'KM', 'PRODUCT_EAV', 'GEM_MAIN_DIAMETER', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(111, 'KM', 'PRODUCT_EAV', 'VINTAGE_FLAG', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(112, 'KM', 'PRODUCT_EAV', 'MOTIF', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL),
(113, 'KM', 'PRODUCT_EAV', 'CASE_NO', '""', '""', 'LABEL_ONLY', 'NULL', NULL, TRUE, 1, NULL);

-- test data
-- INSERT INTO m_data_import_d (
--     profile_id, column_seq, projection_kind, attr_cd, 
--     target_column, cast_type, transform_expr, is_required,
--     import_remarks) VALUES 
-- (1, 0, 'PRODUCT', 'GP_CD', 'group_company_cd', 'TEXT', NULL, TRUE, 'S3より取得した暗黙値（KM）でプログラミング補完'),
-- (1, 1, 'PRODUCT', 'PRODUCT_CD', 'product_cd', 'TEXT', 'trim(@)', TRUE, '商品コード必須'),
-- (1, 2, 'PRODUCT', 'PRODUCT_MANAGEMENT_CD', 'product_management_cd', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 6, 'PRODUCT', 'BRAND', 'brand_id', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 7, 'PRODUCT', 'BRAND', 'brand_nm', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 50, 'PRODUCT', 'CATEGORY_1', 'category_1_id', 'TEXT', 'trim(@)', TRUE, '大カテゴリ必須'),
-- (1, 51, 'PRODUCT', 'CATEGORY_1', 'category_1_nm', 'TEXT', 'trim(@)', TRUE, '大カテゴリ必須'),
-- (1, 52, 'PRODUCT', 'CATEGORY_2', 'category_2_id', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 53, 'PRODUCT', 'CATEGORY_2', 'category_2_nm', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 54, 'PRODUCT', 'CATEGORY_3', 'category_3_id', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 55, 'PRODUCT', 'CATEGORY_3', 'category_3_nm', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 11, 'PRODUCT', 'PRODUCT_STATUS', 'product_status_cd', 'TEXT', 'trim(@)', FALSE, '商品状態必須'),
-- (1, 12, 'PRODUCT', 'PRODUCT_STATUS', 'product_status_nm', 'TEXT', 'trim(@)', FALSE, '商品状態必須'),
-- (1, 13, 'PRODUCT', 'NEW_USED_KBN', 'new_used_kbn', 'TEXT', 'trim(@)', FALSE, '新品区分必須'),
-- (1, 14, 'PRODUCT', 'QUANTITY', 'quantity', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 15, 'PRODUCT', 'STOCK_EXISTENCE', 'stock_existence_cd', 'TEXT', 'trim(@)', FALSE, '在庫有無必須'),
-- (1, 16, 'PRODUCT', 'STOCK_EXISTENCE', 'stock_existence_nm', 'TEXT', 'trim(@)', FALSE, '在庫有無必須'),
-- (1, 17, 'PRODUCT', 'SALE_PERMISSION', 'sale_permission_cd', 'TEXT', 'trim(@)', FALSE, '販売可否必須'),
-- (1, 18, 'PRODUCT', 'SALE_PERMISSION', 'sale_permission_nm', 'TEXT', 'trim(@)', FALSE, '販売可否必須'),
-- (1, 19, 'PRODUCT', 'TRANSFER_STATUS', 'transfer_status', 'TEXT', 'trim(@)', FALSE, '移動状態必須'),
-- (1, 20, 'PRODUCT', 'REPAIR_STATUS', 'repair_status', 'TEXT', 'trim(@)', FALSE, '修理状態必須'),
-- (1, 21, 'PRODUCT', 'RESERVATION_STATUS', 'reservation_status', 'TEXT', 'trim(@)', FALSE, '予約状態必須'),
-- (1, 22, 'PRODUCT', 'CONSIGNMENT_STATUS', 'consignment_status', 'TEXT', 'trim(@)', FALSE, '委託状態必須'),
-- (1, 23, 'PRODUCT', 'SOURCE_ACCEPT_STATUS', 'accept_status', 'TEXT', 'trim(@)', FALSE, '受託状態必須'),
-- (1, 24, 'PRODUCT', 'EC_LISTING_KBN', 'ec_listing_kbn', 'TEXT', 'trim(@)', FALSE, 'EC掲載必須'),
-- (1, 25, 'PRODUCT', 'ASSESSMENT_PRICE_EXCL_TAX', 'assessment_price_excl_tax', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 26, 'PRODUCT', 'ASSESSMENT_PRICE_INCL_TAX', 'assessment_price_incl_tax', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 27, 'PRODUCT', 'ASSESSMENT_TAX_RATE', 'assessment_tax_rate', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 28, 'PRODUCT', 'PURCHASE_PRICE_EXCL_TAX', 'purchase_price_excl_tax', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 29, 'PRODUCT', 'PURCHASE_PRICE_INCL_TAX', 'purchase_price_incl_tax', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 30, 'PRODUCT', 'PURCHASE_TAX_RATE', 'purchase_tax_rate', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 43, 'PRODUCT', 'DISPLAY_PRICE_EXCL_TAX', 'display_price_excl_tax', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 42, 'PRODUCT', 'DISPLAY_PRICE_INCL_TAX', 'display_price_incl_tax', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 33, 'PRODUCT', 'DISPLAY_TAX_RATE', 'display_tax_rate', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 34, 'PRODUCT', 'SALES_PRICE_EXCL_TAX', 'sales_price_excl_tax', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 35, 'PRODUCT', 'SALES_PRICE_INCL_TAX', 'sales_price_incl_tax', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 36, 'PRODUCT', 'SALES_TAX_RATE', 'sales_tax_rate', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 35, 'PRODUCT', 'PURCHASE_RANK', 'purchase_rank', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 36, 'PRODUCT', 'PURCHASE_RANK', 'purchase_rank_nm', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 37, 'PRODUCT', 'SALES_RANK', 'sales_rank', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 38, 'PRODUCT', 'SALES_RANK', 'sales_rank_nm', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 41, 'PRODUCT', 'SALES_CHANNEL_NM', 'sales_channel_nm', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 42, 'PRODUCT', 'SALES_CHANNEL_REGION', 'sales_channel_region', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 43, 'PRODUCT', 'SALES_CHANNEL_METHOD', 'sales_channel_method', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 44, 'PRODUCT', 'SALES_CHANNEL_TARGET', 'sales_channel_target', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 45, 'PRODUCT', 'PURCHASE_CHANNEL_NM', 'purchase_channel_nm', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 46, 'PRODUCT', 'PURCHASE_CHANNEL_REGION', 'purchase_channel_region', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 47, 'PRODUCT', 'PURCHASE_CHANNEL_METHOD', 'purchase_channel_method', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 48, 'PRODUCT', 'PURCHASE_CHANNEL_TARGET', 'purchase_channel_target', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 49, 'PRODUCT', 'STORE_ID', 'store_id', 'TEXT', 'trim(@)', FALSE, '店舗必須'),
-- (1, 50, 'PRODUCT', 'STORE_NM', 'store_nm', 'TEXT', 'trim(@)', FALSE, '店舗必須'),
-- (1, 51, 'PRODUCT', 'CONSIGNOR_GROUP_COMPANY_ID', 'consignor_group_company_id', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 52, 'PRODUCT', 'CONSIGNOR_PRODUCT_CD', 'consignor_product_cd', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 53, 'PRODUCT_EAV', 'SPECIAL_NOTES', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 54, 'PRODUCT_EAV', 'DEFECT_NOTES', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 55, 'PRODUCT_EAV', 'CATALOG_DESC', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 12, 'PRODUCT_EAV', 'PRODUCT_DESC', 'NULL', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 13, 'PRODUCT_EAV', 'PRODUCT_REMARKS', 'NULL', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 57, 'PRODUCT_EAV', 'REPAIR_HISTORY', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 58, 'PRODUCT_EAV', 'BUYER_STAFF', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 59, 'PRODUCT_EAV', 'SUPPLIER_CD', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 60, 'PRODUCT_EAV', 'SUPPLIER_TYPE', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 61, 'PRODUCT_EAV', 'SUPPLIER_STORE', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 47, 'PRODUCT_EAV', 'PURCHASE_DATE', 'NULL', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 63, 'PRODUCT_EAV', 'PROCESSING_FEE', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 39, 'PRODUCT_EAV', 'REFERENCE_PRICE', 'NULL', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 40, 'PRODUCT_EAV', 'REFERENCE_PRICE_UPDATED_AT', 'NULL', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 15, 'PRODUCT_EAV', 'SALES_START_DATE', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 16, 'PRODUCT_EAV', 'SALES_END_DATE', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 28, 'PRODUCT_EAV', 'GENDER', 'NULL', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 69, 'PRODUCT_EAV', 'PRODUCT_ALIAS', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 12, 'PRODUCT_EAV', 'PRODUCT_LINE', 'NULL', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 8, 'PRODUCT_EAV', 'MODEL_NO', 'NULL', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 72, 'PRODUCT_EAV', 'CASE_NO', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 17, 'PRODUCT_EAV', 'DIAL_COLOR', 'NULL', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 17, 'PRODUCT_EAV', 'MAIN_COLOR', 'NULL', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 21, 'PRODUCT_EAV', 'CASE_BAND_MATERIAL', 'NULL', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 18, 'PRODUCT_EAV', 'BAND_COLOR', 'NULL', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 19, 'PRODUCT_EAV', 'DIAL_PATTERN', 'NULL', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 20, 'PRODUCT_EAV', 'CASE_MATERIAL', 'NULL', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 79, 'PRODUCT_EAV', 'MODEL_YEAR', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 22, 'PRODUCT_EAV', 'SIZE_WRIST', 'NULL', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 81, 'PRODUCT_EAV', 'CASE_HEIGHT_ACTUAL', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 26, 'PRODUCT_EAV', 'MOVEMENT', 'NULL', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 23, 'PRODUCT_EAV', 'WEIGHT', 'NULL', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 84, 'PRODUCT_EAV', 'CASE_WIDTH_ACTUAL', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 85, 'PRODUCT_EAV', 'CASE_DEPTH_ACTUAL', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 86, 'PRODUCT_EAV', 'CASE_HEIGHT', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 87, 'PRODUCT_EAV', 'CASE_WIDTH', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 88, 'PRODUCT_EAV', 'CASE_DEPTH', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 89, 'PRODUCT_EAV', 'STANDARD_SIZE', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 29, 'PRODUCT_EAV', 'ACCESSORIES', 'NULL', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 24, 'PRODUCT_EAV', 'WATER_RESIST', 'NULL', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 92, 'PRODUCT_EAV', 'FUNCTIONS', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 93, 'PRODUCT_EAV', 'CASE_SHAPE', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 30, 'PRODUCT_EAV', 'WARRANTY_TYPE', 'NULL', 'TEXT', 'trim(@)', TRUE, NULL),
-- (1, 95, 'PRODUCT_EAV', 'WARRANTY_DATE', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 96, 'PRODUCT_EAV', 'MADE_IN', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 97, 'PRODUCT_EAV', 'SERIAL_NO', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 98, 'PRODUCT_EAV', 'BODY_MATERIAL', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 99, 'PRODUCT_EAV', 'BODY_COLOR', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 100, 'PRODUCT_EAV', 'METAL_MATERIAL', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 101, 'PRODUCT_EAV', 'DATE_CODE', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 102, 'PRODUCT_EAV', 'BODY_PATTERN', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 103, 'PRODUCT_EAV', 'ENGRAVING', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 104, 'PRODUCT_EAV', 'WIDTH', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 105, 'PRODUCT_EAV', 'DEPTH', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 106, 'PRODUCT_EAV', 'HEIGHT', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 107, 'PRODUCT_EAV', 'WIDTH_ACTUAL', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 108, 'PRODUCT_EAV', 'DEPTH_ACTUAL', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 109, 'PRODUCT_EAV', 'HEIGHT_ACTUAL', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 110, 'PRODUCT_EAV', 'CARD_SLOT_COUNT', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 111, 'PRODUCT_EAV', 'POCKET_IN_COUNT', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 112, 'PRODUCT_EAV', 'POCKET_OUT_COUNT', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 113, 'PRODUCT_EAV', 'SERIAL_POSITION', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 114, 'PRODUCT_EAV', 'COLLAB_BRAND', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 115, 'PRODUCT_EAV', 'DESIGN_PERIOD', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 116, 'PRODUCT_EAV', 'SEASON', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 117, 'PRODUCT_EAV', 'PATTERN', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 118, 'PRODUCT_EAV', 'MATERIAL', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 119, 'PRODUCT_EAV', 'SIZE_ACTUAL', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 120, 'PRODUCT_EAV', 'SIZE_NOTE', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 121, 'PRODUCT_EAV', 'BODY_WIDTH', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 122, 'PRODUCT_EAV', 'BODY_LENGTH', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 123, 'PRODUCT_EAV', 'SLEEVE_LENGTH', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 124, 'PRODUCT_EAV', 'SHOULDER_WIDTH', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 125, 'PRODUCT_EAV', 'TOTAL_LENGTH', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 126, 'PRODUCT_EAV', 'WAIST', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 127, 'PRODUCT_EAV', 'INSEAM', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 128, 'PRODUCT_EAV', 'HEEL_HEIGHT', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 129, 'PRODUCT_EAV', 'HEIGHT', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 130, 'PRODUCT_EAV', 'LENGTH', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 131, 'PRODUCT_EAV', 'METAL_PURITY', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 132, 'PRODUCT_EAV', 'GEM_MAIN_MATERIAL', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 133, 'PRODUCT_EAV', 'GEM_SIDE_MATERIAL', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 134, 'PRODUCT_EAV', 'RING_SIZE_JP', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 135, 'PRODUCT_EAV', 'RING_SIZE_US', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 136, 'PRODUCT_EAV', 'ORIGIN', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 137, 'PRODUCT_EAV', 'DIAMOND_COLOR', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 138, 'PRODUCT_EAV', 'GEM_COLOR', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 139, 'PRODUCT_EAV', 'DIAMOND_CUT', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 140, 'PRODUCT_EAV', 'CARAT_MAIN', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 141, 'PRODUCT_EAV', 'CARAT_SIDE', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 142, 'PRODUCT_EAV', 'FLUORESCENCE', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 143, 'PRODUCT_EAV', 'ERA', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 144, 'PRODUCT_EAV', 'CERT_AGENCY', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 145, 'PRODUCT_EAV', 'GEM_TREATMENT', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 146, 'PRODUCT_EAV', 'CERTIFICATE', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 147, 'PRODUCT_EAV', 'DIAMOND_CLARITY', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 148, 'PRODUCT_EAV', 'GEM_MAIN_DIAMETER', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 149, 'PRODUCT_EAV', 'MOTIF', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL),
-- (1, 150, 'PRODUCT_EAV', 'VINTAGE_FLAG', 'NULL', 'TEXT', 'trim(@)', FALSE, NULL);

INSERT INTO m_data_import_d (
    profile_id, column_seq, projection_kind, attr_cd, 
    target_column, cast_type, transform_expr, 
    is_required, import_remarks
) VALUES 
(4, 1, 'EVENT', 'PRODUCT_CD', 'product_cd', 'TEXT', 'trim(@)', TRUE, NULL),
(4, 2, 'EVENT', 'STORE', 'store_id_raw', 'TEXT', 'trim(@)', TRUE, NULL),
(4, 3, 'EVENT', 'STORE', 'store_nm_raw', 'TEXT', 'trim(@)', TRUE, NULL),
(4, 4, 'EVENT', 'NEW_USED_KBN', 'new_used_kbn_raw', 'TEXT', 'trim(@)', TRUE, NULL),
(4, 5, 'EVENT', 'EVENT_TS', 'event_ts_raw', 'TEXT', 'trim(@)', TRUE, NULL),
(4, 6, 'EVENT', 'EVENT_KIND', 'event_kind_raw', 'TEXT', 'trim(@)', TRUE, NULL),
(4, 7, 'EVENT', 'EVENT_QUANTITY', 'qty_raw', 'TEXT', 'trim(@)', TRUE, NULL);
