version: '4.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    restart: always
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user
      POSTGRES_DB: purchase_system
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  pgdata:
  pgadmin_data:
  
  